### ISSUE TITLE
Migration to MSAL

### ISSUE THREAD

**Issue by princjef** [Azure/azure-kusto-go#100]
Is there a plan for this package to be migrated from ADAL to MSAL? The autorest auth packages used for authentication here are ADAL-based and there is no plan for those to upgrade to MSAL (ref: https://github.com/Azure/go-autorest/issues/636). The official guidance is to switch over to using github.com/Azure/azure-sdk-for-go/tree/main/sdk/azidentity which is MSAL-based.

**Comment by element-of-surprise** [comment]
Note on this:

There will not need to be a migration for this.  Kusto's SDK was designed to allow new types of authorization to happen.  ADAL should continue to be supported until such time as ADAL will not work in order to support existing clients.  But also I'm not sure if azidentity currently supports everything that ADAL does.  I wrote the initial Go MSAL implementation and azidentity still has features they want that may be present in ADAL only at this time.  

Also worth noting that azidentity has just rolled their 1.0 release a day ago it looks like.

**Comment by yogilad** [comment]
Since AzIdentity has matured and is using MSAL, we'll try and schedule this in the near future.

**Comment by AsafMah** [comment]
Done! 0.10.0 migrates to azidentity
