### ISSUE TITLE
Azure libraries version 1.x

### ISSUE THREAD

**Issue by AsafMah** [Azure/azure-kusto-go#103]
Azure core & azure identity (and maybe more) recently went to 1.x, while we are still at 0.x.
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore/go.mod
https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azidentity/go.mod

A user had an issue with using these new packages in conjunction with our code.

Moving to the new packages is actually a breaking change - since they require a minimum version of go 1.18

**Comment by element-of-surprise** [comment]
Hey Asaf, just a note on this:

The 1.x versus 0.x is just semantics.  azidentity relies on msal which is still at 0.x.  Moving to 1.x simply means that breaking changes require major version increases and change how you release code.  For some reason it makes people feel better to see a 1.x, but it can also lead to seeing projects do 1.x, 2.x, 3.x, 4.x.....  The decision to move is simply an internal decision on how much trouble you want to deal with on breaking changes and what it means to be 1.x for your team (supports some set of X capabilities).  The thing to remember is that moving to 1.x has real effects on how you manage your Go code afterwards.

But keeping version syncs with another package repo is probably unreasonable for kusto. If they have to go to a 2.0, should kusto do so even if it doesn't need it?  You may not want to upgrade to breaking releases when they do.  And that is something else to keep in mind, if they go to breaking releases and you are past 1.x, you have to bump major versions.

The go version to 1.18 should not be seen as a breaking change.  If you release a new version that requires 1.18, you simply should have to tick up the minor release .  You'd be adding non-breaking features that require a new version of Go.  Requiring a new version of the compiler should not require a major semantic version bump (for 1.x and up code) unless Go itself does a major semantic version upgrade.   All your previous client's code will continue to work, they simply require the new version of Go.  Otherwise when Go no longer supports a compiler version, you'd be upgrading major versions.

As a note, here is Go team's official support model:

_Each major Go release is supported until there are two newer major releases. For example, Go 1.5 was supported until the Go 1.7 release, and Go 1.6 was supported until the Go 1.8 release. We fix critical problems, including [critical security problems](https://go.dev/security), in supported releases as needed by issuing minor revisions (for example, Go 1.6.1, Go 1.6.2, and so on)._

In essence, Go 1.16, which is what kusto supports, is no longer supported by the Go team.  It is probably time to move that marker up to 1.18 for the next release anyways.

**Comment by AsafMah** [comment]
@element-of-surprise 
Thanks for the comment John.
I wanted to ask you about this scenario specifically, if a go module depends on this package, and unrelatedly on the azure 1.x package, would it really break our package?
Can't go handle our dependency and the module's dependency separately?

**Comment by seh-msft** [comment]
Conflicting Go versions required in go.mod will be resolved by taking the highest version in the dependency graph, I believe. 

Examples with - or support for - azidentity rather than autorest would be desirable as autorest will go EOL in March 2023. 

As seen here: https://azure.microsoft.com/updates/support-for-azure-sdk-libraries-that-do-not-conform-to-our-current-azure-sdk-guidelines-will-be-retired-as-of-31-march-2023/

As far as I'm aware, the list of supported Go libraries/SDKs doesn't include a data plane interface for querying Kusto, as this package does. 

The list of 'supported' Go Azure libraries: https://azure.github.io/azure-sdk/#go

**Comment by AsafMah** [comment]
The newest version - 0.10.0 - uses azidentity and azcore at their newest versions. Closing.
