### ISSUE TITLE
queryopts.go - most functions are commented and can't be used

### ISSUE THREAD

**Issue by ronib1** [Azure/azure-kusto-go#107]
Hi,

I need to add queryOptions to my query. The problem is that nothing is exported and I see that I could use the functions in the file queryopts.go, only that for some reason most if it is commented. For example the function CustomQueryOption. Can you please make it useable?

![image](https://user-images.githubusercontent.com/104069171/186131074-5604871a-5f3c-4e4b-b7e6-2b3286976c88.png)

**Comment by yihezkel** [comment]
Hi @ronib1 ,
Thanks for bringing this up. 0.8.0 supports adding all headers, but `request_app_name` and `request_user` don't currently work because of a server-side issue. We have a workaround that @AsafMah will be adding shortly. Please check back in a few days, and once the new version is released you should be able to set these properties.

We'll close this issue for now, feel free to reopen if that doesn't work.
