### ISSUE TITLE
NewStatementBuilder mentioned in the docs but does not exist in the code

### ISSUE THREAD

**Issue by grzn** [Azure/azure-kusto-go#173]
`NewStatementBuilder` looks great in the docs, too bad it is not really implemented in the code...

**Comment by AsafMah** [comment]
We are still working on this, the master branch shows the latest changes but not the latest release.

We expect a release this week (and if not it might take another couple of weeks since we have a holiday).

Either way, you can direct your go.mod file directly to a specific commit or branch, but be careful as non tagged versions might be buggy.
