### ISSUE TITLE
If Authorizer does not have "resource" set, should just error.

### ISSUE THREAD

**Issue by element-of-surprise** [Azure/azure-kusto-go#44]
We recommend using the Config instead of Authorizer because of the whole resource not getting set.

I *think* there was a reason for us to not set it in the Authorizer (maybe it was so we had an escape hatch for some weird corner case??). 

But we should try to check to see if it has a resource set.  Baring that, we should add output to the error so it says:
"DID YOU SET THE RESOURCE IN YOUR AUTHORIZER???".

The deny message from Kusto will not tell you that your resource was not set.

**Comment by 0xThiebaut** [comment]
Documenting this requirement on the `kusto.New` method will also spare developers debugging time 😉

**Comment by AsafMah** [comment]
Sadly by the point kusto.New gets the object, it's already too late - 
auth.NewAuthorizerFromCLIWithResource and auth.NewAuthorizerFromCLI both return a BearerAuthorizer whose token has the "Resource" property as null.

The only way to check is to decode the JWT, which I think is out of scope for our library.

@yogilad Suggests we'll make our own abstraction layer for tokens like in the other SDKs, and since we can control the interface there we can circumvent this issue.
