### ISSUE TITLE
`row.Columns` populates column names instead of values

### ISSUE THREAD

**Issue by w1ndy** [Azure/azure-kusto-go#72]
Documentation says:

> The value of the kth column will be decoded into the kth argument to Columns

but actually the column names are decoded into the arguments.

https://github.com/Azure/azure-kusto-go/blob/b89f1684a83556dc7c03c161afacad5b29f6a167/kusto/data/table/table.go#L77-L104

**Comment by w1ndy** [comment]
I looked into the test and found that `Columns` seems to retrieve column names by design... I wonder why this method is needed since there already exists similar ones like `ColumnNames` and `ColumnTypes`. Maybe we can change its behavior to retrieve values or replace it with a new method called `Values`?

**Comment by element-of-surprise** [comment]
This is a leave over from my early design work that has somehow managed to stay in here.  Kudos for finding it.

When I was doing the first drafts I was looking at both database/sql,  spanner's and a few other APIs.  

I blame too many late nights for this, but this is really a completely wrong implementation.  The kind of thing I should have said, what the hell are you doing.......

What this should be doing is exactly what you said, grabbing the value from those positional locations in the row.

We should probably have this functionality, but this is now kind of a pickle. It can't be Values, we offer an attribute that provides the Values.  We can't change it, because that could cause someone some consequences.

I'm not the current maintainer, so I've sent this up the chain to see what they want to do.

**Comment by w1ndy** [comment]
@element-of-surprise @yogilad Thanks for your effort! I think this issue may be addressed as follows:

1. Decouple the logic of `boolConvert`, `dateTimeConvert`, etc from `row.ToStruct` so they can be reused for any given `reflect.Type` and `reflect.Value`, instead of being tied to struct fields;
2. Add a new method (could be called `ExtractValues` or whatever) to read values from a row easily.

How do you like these changes? I can help implement them.

**Comment by w1ndy** [comment]
Fixed by #75
